version: '3'

services:
  nginx:
    image: nginx:latest
    build: ./nginx/
    links:
      - backend
      - frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
  backend:
    build: ./backend
    image: flask:latest
    environment:
      - "MODE=dev"
    ports:
      - "8081:8081"
    # For development
    volumes:
      - "./backend:/usr/src/app"
    links:
      - db
  frontend:
    build: ./frontend
    image: angular2:latest
    ports:
      - "4200:4200"
      - "49152:49152"
    # For development
    volumes:
      - "./frontend:/frontend"
  db:
    restart: always
    build: ./db
    image: mongodb:latest